# permissions for end users to view acmcertificateimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: acmcertificateimport-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-acm-importer
    app.kubernetes.io/part-of: kube-acm-importer
    app.kubernetes.io/managed-by: kustomize
  name: acmcertificateimport-viewer-role
rules:
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports/status
  verbs:
  - get
