---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports/finalizers
  verbs:
  - update
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports/status
  verbs:
  - get
  - patch
  - update
