apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-acm-importer.fullname" . }}-manager-role
  labels:
  {{- include "kube-acm-importer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports/finalizers
  verbs:
  - update
- apiGroups:
  - acm.kubespress.com
  resources:
  - acmcertificateimports/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-acm-importer.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-acm-importer
    app.kubernetes.io/part-of: kube-acm-importer
  {{- include "kube-acm-importer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kube-acm-importer.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kube-acm-importer.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'