apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-acm-importer.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kube-acm-importer
    app.kubernetes.io/part-of: kube-acm-importer
    control-plane: controller-manager
  {{- include "kube-acm-importer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "kube-acm-importer.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}