apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-acm-importer.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-acm-importer
    app.kubernetes.io/part-of: kube-acm-importer
  {{- include "kube-acm-importer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}